apiVersion: apps/v1
kind: Deployment
metadata:
  name: music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: music
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "$ProxySite"
        - name: Vmess_UUID
          value: "$Vmess_UUID"
        - name: Vmess_Path
          value: "$Vmess_Path"
        - name: Share_Path
          value: "$Share_Path"
